#!/usr/bin/env bash
# displays Holberton School 10 times.

counter=1
while [ $counter -lt 101 ]
do
	if [ $((counter%15)) = 0 ]
	then
        	echo "FizzBuzz"
	elif [ $((counter%3)) = 0 ]
    	then
        	echo "Fizz"
	elif [ $((counter%5)) = 0 ]
	then
        	echo "Buzz"
	else
        	echo "$counter"
	fi
	((counter++)) || true
done
