#!/usr/bin/env bash
# displays Best School 10 times.

COUNTER=0
while [ $COUNTER -lt 11 ]
do
    if [ $COUNTER = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((COUNTER++)) || true
done
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Privacy

