#!/usr/bin/env bash
# displays the time for 12 hour and 59 min.

hour=0
while [ $hour -lt 13 ]
do
    echo "Hour: $hour"
    min=1
    while [ $min -lt 60 ]
    do
        echo $min
	((min++)) || true
    done
    ((hour++)) || true
done
